SIGEP/Models/HostingEntity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SIGEP.models
{
    public partial class HostingEntity
    {
        public HostingEntity()
        {
            Activities = new HashSet<Activities>();
            Message = new HashSet<Message>();
        }

        public int IdHostingEntity { get; set; }

   
        [Required]
        [RegularExpression(@"[a-zA-Z\s]+$", ErrorMessage = "Nome Inválido")]
        [MinLength(8, ErrorMessage = "Nome Demasiado Curto")]
        [MaxLength(40, ErrorMessage = "Nome Demasiado Longo")]
        public string Name { get; set; }

        [Required]
        [RegularExpression("^[0-9]{9}$", ErrorMessage = "Telefone Inválido") ]
        public int? Telephone { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "Email Inválido")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [MinLength(8, ErrorMessage = "Morada Demasiado Curta")]
        [MaxLength(45, ErrorMessage = "Morada Demasiado Longa")]
        public string Address { get; set; }

        [RegularExpression("[0-9]{1,}")]
        [Display(Name="Representante da Entidade")]
        public int? UserRep { get; set; }

        public virtual Users UserRepNavigation { get; set; }
        public virtual ICollection<Activities> Activities { get; set; }
        public virtual ICollection<Message> Message { get; set; }
    }
}

SIGEP/Controllers/HostingEntitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SIGEP.models;

namespace SIGEP.Controllers
{
    public class HostingEntitiesController : Controller
    {
        private readonly SWDBContext _context;

        public HostingEntitiesController(SWDBContext context)
        {
            _context = context;
        }

        // GET: HostingEntities
        public async Task<IActionResult> Index()
        {
            var sWDBContext = _context.HostingEntity.Include(h => h.UserRepNavigation);
            return View(await sWDBContext.ToListAsync());
        }

        // GET: HostingEntities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hostingEntity = await _context.HostingEntity
                .Include(h => h.UserRepNavigation)
                .FirstOrDefaultAsync(m => m.IdHostingEntity == id);
            if (hostingEntity == null)
            {
                return NotFound();
            }

            return View(hostingEntity);
        }

        // GET: HostingEntities/Create
        public IActionResult Create()
        {
            //query to check representative type missing
            ViewData["UserRep"] = new SelectList(_context.Users, "UserNumber", "Name");
            return View();
        }

        // POST: HostingEntities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdHostingEntity,Name,Telephone,Email,Address,UserRep")] HostingEntity hostingEntity)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hostingEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //query to check representative type missing
            ViewData["UserRep"] = new SelectList(_context.Users, "UserNumber", "Name", hostingEntity.UserRep);
            return View(hostingEntity);
        }

        // GET: HostingEntities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hostingEntity = await _context.HostingEntity.FindAsync(id);
            if (hostingEntity == null)
            {
                return NotFound();
            }
            //query to check representative type missing
            ViewData["UserRep"] = new SelectList(_context.Users, "UserNumber", "Name", hostingEntity.UserRep);
            return View(hostingEntity);
        }

        // POST: HostingEntities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdHostingEntity,Name,Telephone,Email,Address,UserRep")] HostingEntity hostingEntity)
        {
            if (id != hostingEntity.IdHostingEntity)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hostingEntity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HostingEntityExists(hostingEntity.IdHostingEntity))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //query to check representative type missing
            ViewData["UserRep"] = new SelectList(_context.Users, "UserNumber", "Name", hostingEntity.UserRep);
            return View(hostingEntity);
        }

        // GET: HostingEntities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hostingEntity = await _context.HostingEntity
                .Include(h => h.UserRepNavigation)
                .FirstOrDefaultAsync(m => m.IdHostingEntity == id);
            if (hostingEntity == null)
            {
                return NotFound();
            }

            return View(hostingEntity);
        }

        // POST: HostingEntities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hostingEntity = await _context.HostingEntity.FindAsync(id);
            _context.HostingEntity.Remove(hostingEntity);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HostingEntityExists(int id)
        {
            return _context.HostingEntity.Any(e => e.IdHostingEntity == id);
        }
    }
}

SIGEP/Views/HostingEntities/Create.cshtml
@model SIGEP.models.HostingEntity

@{
    ViewData["Title"] = "Create";
}
@section css {
    <link rel="stylesheet" href="~/css/users.css" />
}

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row d-flex align-items-center flex-wrap">
            <div class="col-md-7">
                <h1 class="h2" id="titlePage">Criar Entidade</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb d-flex justify-content-end">
                    <li class="breadcrumb-item"><a href="/Home">Home</a></li>
                    <li class="breadcrumb-item active">Entidades</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="content">
    <div class="container">
        <div class="row bar">
            <div class="col-lg-8 offset-lg-2">
                <div style="margin-top: 5%;">
                    <h2 class="text-uppercase">Inserir uma Entidade</h2>
                    <hr>
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Telephone" class="control-label"></label>
                            <input asp-for="Telephone" class="form-control" />
                            <span asp-validation-for="Telephone" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="control-label"></label>
                            <input asp-for="Address" class="form-control" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="UserRep" class="control-label"></label>
                            <select asp-for="UserRep" class="form-control" asp-items="ViewBag.UserRep"></select>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Inserir" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<hr />


<div>
    <a asp-action="Index">Back to List</a>
</div>

SIGEP/Views/HostingEntities/Delete.cshtml
@model SIGEP.models.HostingEntity

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HostingEntity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserRepNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserRepNavigation.Address)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdHostingEntity" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SIGEP/Views/HostingEntities/Details.cshtml
@model SIGEP.models.HostingEntity

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>HostingEntity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserRepNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserRepNavigation.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdHostingEntity">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SIGEP/Views/HostingEntities/Edit.cshtml
@model SIGEP.models.HostingEntity

@{
    ViewData["Title"] = "Edit";
}
@section css {
    <link rel="stylesheet" href="~/css/users.css" />
}

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row d-flex align-items-center flex-wrap">
            <div class="col-md-7">
                <h1 class="h2" id="titlePage">Editar Entidades</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb d-flex justify-content-end">
                    <li class="breadcrumb-item"><a href="/Home">Home</a></li>
                    <li class="breadcrumb-item active">Entidades</li>
                    <li class="breadcrumb-item active">Editar</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="content">
    <div class="container">
        <div class="row bar">
            <div class="col-lg-8 offset-lg-2">
                <div style="margin-top: 5%;">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="IdHostingEntity" />
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Telephone" class="control-label"></label>
                            <input asp-for="Telephone" class="form-control" />
                            <span asp-validation-for="Telephone" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="control-label"></label>
                            <input asp-for="Address" class="form-control" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="UserRep" class="control-label"></label>
                            <select asp-for="UserRep" class="form-control" asp-items="ViewBag.UserRep"></select>
                            <span asp-validation-for="UserRep" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Guardar" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SIGEP/Views/HostingEntities/Index.cshtml
@model IEnumerable<SIGEP.models.HostingEntity>

@{
    ViewData["Title"] = "Index";
}
@section css {
    <link rel="stylesheet" href="~/css/users.css" />
}

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row d-flex align-items-center flex-wrap">
            <div class="col-md-7">
                <h1 class="h2" id="titlePage">Entidades</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb d-flex justify-content-end">
                    <li class="breadcrumb-item"><a href="/Home">Home</a></li>
                    <li class="breadcrumb-item active">Entidades</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div style="margin-top: 5%;">
                    <h2 class="text-uppercase">Consultar Entidades</h2>
                    <hr>
                    <div class="box mt-0 pb-0 no-horizontal-padding">
                        <div class="box-footer d-flex justify-content-between align-items-center">
                            <div class="left-col">
                                <button class="btn btn-template-main" data-toggle="modal" data-target="#hosting-entity-modal" type="button" id="createEntity">Inserir Entidade</button>
                            </div>
                            @section scripts{
                                <script>
                                document.getElementById("createEntity").addEventListener('click', function () {
                                location.href = '@Url.Action("Create", "HostingEntities")';
                                });
                                </script>
                            }
                            <p class="text-muted lead"> Pesquisar por :  </p>
                            <p class="text-muted lead">
                                <input id="text" type="text" class="form-control">
                            </p>
                            <div class="right-col">
                                <button class="btn btn-template-main" type="button">Excluír Seleccionados</button>
                            </div>
                        </div>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Telephone)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Email)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Address)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.UserRep)
                                </th>
                                <th>Editar</th>
                                <th>
                                    <div class="checkbox">
                                        <label><input type="checkbox"> Todos</label>
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Telephone)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Email)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Address)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserRepNavigation.Name)
                                    </td>
                                    <td>
                                        <a asp-action="Edit" asp-route-id="@item.IdHostingEntity">Edit</a> |
                                        <a asp-action="Details" asp-route-id="@item.IdHostingEntity">Details</a> |
                                        <a asp-action="Delete" asp-route-id="@item.IdHostingEntity">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>