SIGEP/Models/ActivityTypes.cs
using System;
using System.Collections.Generic;

namespace SIGEP.models
{
    public partial class ActivityTypes
    {
        public ActivityTypes()
        {
            Activities = new HashSet<Activities>();
        }

        public int IdType { get; set; }
        public string Type { get; set; }

        public virtual ICollection<Activities> Activities { get; set; }
    }
}

SIGEP/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SIGEP.models;

namespace SIGEP.Controllers
{
    public class ActivitiesController : Controller
    {
        private readonly SWDBContext _context;

        public ActivitiesController(SWDBContext context)
        {
            _context = context;
        }

        // GET: Activities
        public async Task<IActionResult> Index()
        {
            var sWDBContext = _context.Activities.Include(a => a.IdActivityTypesNavigation).Include(a => a.IdHostingEntityNavigation).Include(a => a.IdStudentNavigation);
            return View(await sWDBContext.ToListAsync());
        }

        // GET: Activities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activities = await _context.Activities
                .Include(a => a.IdActivityTypesNavigation)
                .Include(a => a.IdHostingEntityNavigation)
                .Include(a => a.IdStudentNavigation)
                .FirstOrDefaultAsync(m => m.IdActivity == id);
            if (activities == null)
            {
                return NotFound();
            }

            return View(activities);
        }

        // GET: Activities/Create
        public IActionResult Create()
        {
            ViewData["IdActivityTypes"] = new SelectList(_context.ActivityTypes, "IdType", "Type");
            ViewData["IdHostingEntity"] = new SelectList(_context.HostingEntity, "IdHostingEntity", "Name");
            ViewData["IdStudent"] = new SelectList(_context.Users, "UserNumber", "Name");
            return View();
        }

        // POST: Activities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdActivity,IdHostingEntity,IdActivityTypes,IdStudent,Title,VacancyLimit,Location,MainRequirements,ConfidentialityRequirements,UsedTechs,Observations,Description,Objectives,WorkTime")] Activities activities)
        {
            if (ModelState.IsValid)
            {
                _context.Add(activities);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdActivityTypes"] = new SelectList(_context.ActivityTypes, "IdType", "Type", activities.IdActivityTypes);
            ViewData["IdHostingEntity"] = new SelectList(_context.HostingEntity, "IdHostingEntity", "Address", activities.IdHostingEntity);
            ViewData["IdStudent"] = new SelectList(_context.Users, "UserNumber", "Address", activities.IdStudent);
            return View(activities);
        }

        // GET: Activities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activities = await _context.Activities.FindAsync(id);
            if (activities == null)
            {
                return NotFound();
            }
            ViewData["IdActivityTypes"] = new SelectList(_context.ActivityTypes, "IdType", "Type", activities.IdActivityTypes);
            ViewData["IdHostingEntity"] = new SelectList(_context.HostingEntity, "IdHostingEntity", "Address", activities.IdHostingEntity);
            ViewData["IdStudent"] = new SelectList(_context.Users, "UserNumber", "Address", activities.IdStudent);
            return View(activities);
        }

        // POST: Activities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdActivity,IdHostingEntity,IdActivityTypes,IdStudent,Title,VacancyLimit,Location,MainRequirements,ConfidentialityRequirements,UsedTechs,Observations,Description,Objectives,WorkTime")] Activities activities)
        {
            if (id != activities.IdActivity)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(activities);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActivitiesExists(activities.IdActivity))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdActivityTypes"] = new SelectList(_context.ActivityTypes, "IdType", "Type", activities.IdActivityTypes);
            ViewData["IdHostingEntity"] = new SelectList(_context.HostingEntity, "IdHostingEntity", "Address", activities.IdHostingEntity);
            ViewData["IdStudent"] = new SelectList(_context.Users, "UserNumber", "Address", activities.IdStudent);
            return View(activities);
        }

        // GET: Activities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var activities = await _context.Activities
                .Include(a => a.IdActivityTypesNavigation)
                .Include(a => a.IdHostingEntityNavigation)
                .Include(a => a.IdStudentNavigation)
                .FirstOrDefaultAsync(m => m.IdActivity == id);
            if (activities == null)
            {
                return NotFound();
            }

            return View(activities);
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var activities = await _context.Activities.FindAsync(id);
            _context.Activities.Remove(activities);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActivitiesExists(int id)
        {
            return _context.Activities.Any(e => e.IdActivity == id);
        }
    }
}

SIGEP/Views/Activities/Create.cshtml
@model SIGEP.models.Activities

@{
    ViewData["Title"] = "Create";
}

@section css {
    <link rel="stylesheet" href="~/css/users.css" />
}

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row d-flex align-items-center flex-wrap">
            <div class="col-md-7">
                <h1 class="h2" id="titlePage">Criar Atividade</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb d-flex justify-content-end">
                    <li class="breadcrumb-item"><a href="/Home">Home</a></li>
                    <li class="breadcrumb-item active">Atividades</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="content">
    <div class="container">
        <div class="row bar">
            <div class="col-lg-8 offset-lg-2">
                <div style="margin-top: 5%;">
                    <h2 class="text-uppercase">Inserir um Estágio/Projeto</h2>
                    <hr />
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="IdHostingEntity" class="control-label"></label>
                                <select asp-for="IdHostingEntity" class="form-control" asp-items="ViewBag.IdHostingEntity"></select>
                            </div>
                            <div class="form-group">
                                <label asp-for="IdActivityTypes" class="control-label"></label>
                                <select asp-for="IdActivityTypes" class="form-control" asp-items="ViewBag.IdActivityTypes"></select>
                            </div>
                            @*<div class="form-group">
                                <label asp-for="IdStudent" class="control-label"></label>
                                <select asp-for="IdStudent" class="form-control" asp-items="ViewBag.IdStudent"></select>
                            </div>*@
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="VacancyLimit" class="control-label"></label>
                                <input asp-for="VacancyLimit" class="form-control" />
                                <span asp-validation-for="VacancyLimit" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Location" class="control-label"></label>
                                <input asp-for="Location" class="form-control" />
                                <span asp-validation-for="Location" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MainRequirements" class="control-label"></label>
                                <textarea  asp-for="MainRequirements" rows="3" class="form-control"></textarea>
                                <span asp-validation-for="MainRequirements" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ConfidentialityRequirements" class="control-label"></label>
                                <textarea asp-for="ConfidentialityRequirements" rows="4" class="form-control"></textarea>
                                <span asp-validation-for="ConfidentialityRequirements" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="UsedTechs" class="control-label"></label>
                                <textarea asp-for="UsedTechs" rows="4" class="form-control"></textarea>
                                <span asp-validation-for="UsedTechs" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Observations" class="control-label"></label>
                                <textarea asp-for="Observations" rows="4" class="form-control"></textarea>
                                <span asp-validation-for="Observations" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Objectives" class="control-label"></label>
                                <textarea asp-for="Objectives" rows="3" class="form-control"></textarea>
                                <span asp-validation-for="Objectives" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="WorkTime" class="control-label"></label>
                                <input asp-for="WorkTime" class="form-control" />
                                <span asp-validation-for="WorkTime" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </form>
                </div>

                <div>
                    <a asp-action="Index">Back to List</a>
                </div>


            </div>
        </div>
    </div>
</div>

SIGEP/Views/Activities/Delete.cshtml
@model SIGEP.models.Activities

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Activities</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VacancyLimit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VacancyLimit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MainRequirements)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MainRequirements)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConfidentialityRequirements)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConfidentialityRequirements)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UsedTechs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UsedTechs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observations)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observations)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Objectives)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Objectives)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WorkTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WorkTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdActivityTypesNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdActivityTypesNavigation.Type)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdHostingEntityNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdHostingEntityNavigation.Address)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdStudentNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdStudentNavigation.Address)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdActivity" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SIGEP/Views/Activities/Details.cshtml
@model SIGEP.models.Activities

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Activities</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VacancyLimit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VacancyLimit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MainRequirements)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MainRequirements)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ConfidentialityRequirements)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ConfidentialityRequirements)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UsedTechs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UsedTechs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Observations)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Observations)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Objectives)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Objectives)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WorkTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WorkTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdActivityTypesNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdActivityTypesNavigation.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdHostingEntityNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdHostingEntityNavigation.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdStudentNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdStudentNavigation.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdActivity">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SIGEP/Views/Activities/Edit.cshtml
@model SIGEP.models.Activities

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Activities</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdActivity" />
            <div class="form-group">
                <label asp-for="IdHostingEntity" class="control-label"></label>
                <select asp-for="IdHostingEntity" class="form-control" asp-items="ViewBag.IdHostingEntity"></select>
                <span asp-validation-for="IdHostingEntity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdActivityTypes" class="control-label"></label>
                <select asp-for="IdActivityTypes" class="form-control" asp-items="ViewBag.IdActivityTypes"></select>
                <span asp-validation-for="IdActivityTypes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdStudent" class="control-label"></label>
                <select asp-for="IdStudent" class="form-control" asp-items="ViewBag.IdStudent"></select>
                <span asp-validation-for="IdStudent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VacancyLimit" class="control-label"></label>
                <input asp-for="VacancyLimit" class="form-control" />
                <span asp-validation-for="VacancyLimit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MainRequirements" class="control-label"></label>
                <input asp-for="MainRequirements" class="form-control" />
                <span asp-validation-for="MainRequirements" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfidentialityRequirements" class="control-label"></label>
                <input asp-for="ConfidentialityRequirements" class="form-control" />
                <span asp-validation-for="ConfidentialityRequirements" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsedTechs" class="control-label"></label>
                <input asp-for="UsedTechs" class="form-control" />
                <span asp-validation-for="UsedTechs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Observations" class="control-label"></label>
                <input asp-for="Observations" class="form-control" />
                <span asp-validation-for="Observations" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Objectives" class="control-label"></label>
                <input asp-for="Objectives" class="form-control" />
                <span asp-validation-for="Objectives" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkTime" class="control-label"></label>
                <input asp-for="WorkTime" class="form-control" />
                <span asp-validation-for="WorkTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SIGEP/Views/Activities/Index.cshtml
@model IEnumerable<SIGEP.models.Activities>

@{
    ViewData["Title"] = "Index";
}

@section css {
    <link rel="stylesheet" href="~/css/users.css" />
}

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row d-flex align-items-center flex-wrap">
            <div class="col-md-7">
                <h1 class="h2" id="titlePage">Atividades</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb d-flex justify-content-end">
                    <li class="breadcrumb-item"><a href="/Home">Home</a></li>
                    <li class="breadcrumb-item active">Atividades</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="content">
    <div class="container-fluid">
        <div class="row" style="width:100%;">
            <div class="col-lg-12">
                <div style="margin-top: 5%;">
                    <h2 class="text-uppercase">Consultar Entidades</h2>
                    <hr>
                    <div class="box mt-0 pb-0 no-horizontal-padding">
                        <div class="box-footer d-flex justify-content-between align-items-center">
                            <div class="left-col">
                                <button class="btn btn-template-main" data-toggle="modal" data-target="#hosting-entity-modal" type="button" id="createActivity">Inserir Atividade</button>
                            </div>
                            @section scripts{
                                <script>
                                document.getElementById("createActivity").addEventListener('click', function () {
                                location.href = '@Url.Action("Create", "Activities")';
                                });
                                </script>
                            }
                            <p class="text-muted lead"> Pesquisar por :  </p>
                            <p class="text-muted lead">
                                <input id="text" type="text" class="form-control">
                            </p>
                            <div class="right-col">
                                <button class="btn btn-template-main" type="button">Excluír Seleccionados</button>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Title)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Location)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Description)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.IdActivityTypesNavigation.Type)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.IdHostingEntityNavigation.Telephone)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.IdStudentNavigation.Name)
                                    </th>
                                    <th>Editar</th>
                                    <th>
                                        <div class="checkbox">
                                            <label><input type="checkbox"> Todos</label>
                                        </div>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Title)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Location)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.IdActivityTypesNavigation.Type)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IdHostingEntityNavigation.Telephone)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IdStudentNavigation.Name)
                                    </td>
                                    <td>
                                        <a asp-action="Edit" asp-route-id="@item.IdActivity">Edit</a> |
                                        <a asp-action="Details" asp-route-id="@item.IdActivity">Details</a> |
                                        <a asp-action="Delete" asp-route-id="@item.IdActivity">Delete</a>
                                    </td>
                                    <td>
                                        <div class="checkbox">
                                            <input type="checkbox">
                                            <a href="#"><i class="fa fa-trash-o"></i></a>
                                        </div>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>